[package]
name = "journal-gateway"
version = "0.1.0"
license = "MIT"
authors = ["Juhasz Sandor <blackghost1987@gmail.com>"]

[dependencies]
url = "1.4.1"
hyper = "0.10.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"